apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: helloworld-nodejs
  namespace: default
spec:
  template:
    spec:
      containers:
      - image: otomi/helloworld-nodejs:1.2.10
        env:
        - name: TARGET
          value: "Universe"
